name: zekr
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  path: ^1.9.0
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.1
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.13
  audio_video_progress_bar: ^2.0.3
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  percent_indicator: ^4.2.4
  shared_preferences: ^2.3.3
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  open_dir: ^0.0.2+1
  open_file: ^3.5.10
  file_manager: ^1.0.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^3.0.1
  workmanager: ^0.5.2
  sqflite: ^2.4.1
  intl: ^0.19.0
  jhijri: ^1.0.0
  http: ^1.2.2
  html: ^0.15.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/athkarLogo.png"

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
